
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 01 10:46:04 BST 2012
//----------------------------------------------------

package org.jboss.byteman.rule.grammar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 46;
  public static final int GE = 25;
  public static final int UMINUS = 40;
  public static final int LPAREN = 8;
  public static final int SEMI = 12;
  public static final int MINUS = 36;
  public static final int BXOR = 32;
  public static final int RPAREN = 9;
  public static final int BOOLEAN_LITERAL = 45;
  public static final int NOT = 38;
  public static final int AND = 20;
  public static final int LT = 21;
  public static final int LSH = 29;
  public static final int OR = 19;
  public static final int COMMA = 13;
  public static final int THROW = 7;
  public static final int BAND = 31;
  public static final int DIV = 34;
  public static final int PLUS = 35;
  public static final int NULL_LITERAL = 42;
  public static final int ASSIGN = 15;
  public static final int IF = 3;
  public static final int DOT = 14;
  public static final int LE = 22;
  public static final int BIND = 2;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int URSH = 27;
  public static final int MOD = 37;
  public static final int TWIDDLE = 39;
  public static final int EQ = 23;
  public static final int RSH = 28;
  public static final int COLON = 18;
  public static final int BOR = 30;
  public static final int LSQUARE = 10;
  public static final int RSQUARE = 11;
  public static final int DOLLAR = 41;
  public static final int NE = 24;
  public static final int TERN_IF = 17;
  public static final int NOTHING = 5;
  public static final int FLOAT_LITERAL = 43;
  public static final int GT = 26;
  public static final int DO = 4;
  public static final int IDENTIFIER = 47;
  public static final int INTEGER_LITERAL = 44;

  /* non terminals */
  static final int NT$2 = 42;
  static final int NT$1 = 41;
  static final int NT$0 = 40;
  static final int condition = 7;
  static final int new_expr = 22;
  static final int meth_expr = 20;
  static final int new_array_idx_list = 23;
  static final int array_expr = 17;
  static final int eca_rule = 0;
  static final int eca_error_in_action = 36;
  static final int expr_field_expr = 19;
  static final int binding = 5;
  static final int ca_error_in_condition = 38;
  static final int name = 30;
  static final int bind_sym = 6;
  static final int ternary_oper_expr = 14;
  static final int action_expr = 10;
  static final int array_idx = 27;
  static final int simple_expr = 24;
  static final int action_expr_list = 9;
  static final int field_expr = 18;
  static final int ca_error = 37;
  static final int binary_oper_expr = 15;
  static final int eca_error = 33;
  static final int arraydims = 29;
  static final int ca = 2;
  static final int eca_error_in_event = 34;
  static final int unary_oper_expr = 16;
  static final int actions = 8;
  static final int expr_meth_expr = 21;
  static final int eca_error_in_condition = 35;
  static final int path = 32;
  static final int expr = 13;
  static final int typename = 28;
  static final int null_expr = 25;
  static final int array_idx_list = 26;
  static final int bindings = 4;
  static final int throw_return_expr = 11;
  static final int ca_error_in_action = 39;
  static final int simple_name = 31;
  static final int expr_list = 12;
  static final int eca = 1;
  static final int event = 3;
}

